# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

- task: CmdLine@2
  inputs:
    script: 'dotnet tool install -g dotnet-script'

- task: CmdLine@2
  inputs:
    script: './build.sh deploy'
    workingDirectory: '$(Build.SourcesDirectory)/multi-cloud-ai-workflow'

