# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:

- task: CmdLine@2
  displayName: 'Apply execution permissions'
  inputs: 
    script: 'chmod -R 755 $(Build.SourcesDirectory)/multi-cloud-ai-workflow'

- task: CmdLine@2
  displayName: 'Build/Deploy'
  inputs:
    script: 'dotnet tool install -g dotnet-script && ./build.sh deploy'
    workingDirectory: '$(Build.SourcesDirectory)/multi-cloud-ai-workflow'

